(* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. *)

let rec fib (prev : int) (curr : int) (sum : int) : int =
  let next = prev + curr in
  if next < 4000000 then
    if (next mod 2) = 0 then
      (fib curr next (sum + next))
    else begin
      (fib curr next sum)
    end
  else
    sum;;

Printf.printf "%d\n" (fib 1 2 2);;

